

[tool.poetry]
name = 'findjobo'
version = '1.2.3'

[tool.poetry.dependencies]
python = '^3.9'


[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'

[project]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}