# Generated by Django 4.1.3 on 2022-11-18 16:34

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.TextField(max_length=100)),
                ('description', djrichtextfield.models.RichTextField()),
                ('company', models.TextField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='findjoboapp.city')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findjoboapp.category')),
            ],
        ),
    ]
