# Generated by Django 4.1.3 on 2022-12-10 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjoboapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
