# Generated by Django 4.1.3 on 2022-11-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findjoboapp', '0002_job_id_alter_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findjoboapp.city'),
        ),
    ]
