# Generated by Django 4.1.3 on 2022-11-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjoboapp', '0004_alter_job_category_alter_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_url',
            field=models.URLField(default='http://findjobo.com'),
            preserve_default=False,
        ),
    ]
